name: tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        env:
          - { php: "7.4" }
          - { php: "8.0" }
          - { php: "8.1" }
          - { php: "8.2" }
    name: Linting on PHP${{ matrix.env.php }}
    steps:
      - uses: actions/checkout@v3
      - name: Add GITHUB_TOKEN if available
        run: if [ -n "${{secrets.GITHUB_TOKEN}}" ]; then composer config github-oauth.github.com ${{secrets.GITHUB_TOKEN}}; fi;
      - name: Install testing system
        run: Build/Scripts/runTests.sh -p ${{ matrix.env.php }} -s composerUpdate
      - name: TypoScript lint
        run: Build/Scripts/runTests.sh -p ${{ matrix.env.php }} -s typoScriptLint
      - name: Lint php
        run: Build/Scripts/runTests.sh -n -p ${{ matrix.env.php }} -s cgl
      - name: CGL (php-cs-fixer)
        run: Build/Scripts/runTests.sh -n -p ${{ matrix.env.php }} -s cgl
      - name: phpstan
        run: Build/Scripts/runTests.sh -n -p ${{ matrix.env.php }} -s phpstan

  tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        env:
          - { php: "7.4", TYPO3_VERSION: 11 }
          - { php: "8.0", TYPO3_VERSION: 11 }
          - { php: "8.1", TYPO3_VERSION: 11 }
          - { php: "8.2", TYPO3_VERSION: 11 }
          - { php: "8.1", TYPO3_VERSION: 12 }
          - { php: "8.2", TYPO3_VERSION: 12 }
    name: Tests on PHP${{ matrix.env.php }} / TYPO3 ${{ matrix.env.TYPO3_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: Add GITHUB_TOKEN if available
        run: if [ -n "${{secrets.GITHUB_TOKEN}}" ]; then composer config github-oauth.github.com ${{secrets.GITHUB_TOKEN}}; fi;
      - name: Install testing system
        run: Build/Scripts/runTests.sh -p ${{ matrix.env.php }} -t ${{ matrix.env.TYPO3_VERSION }} -s composerUpdate
      - name: Functional Tests with sqlite
        run: Build/Scripts/runTests.sh -p ${{ matrix.env.php }} -t ${{ matrix.env.TYPO3_VERSION }} -d sqlite -s functional
